// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpm160XaqauvFswuHfxUSxR3s07pTcUZU',
    appId: '1:1005145227491:web:f60f7355fca62e838c85d6',
    messagingSenderId: '1005145227491',
    projectId: 'rent-bee-498712',
    authDomain: 'rent-bee-498712.firebaseapp.com',
    storageBucket: 'rent-bee-498712.firebasestorage.app',
    measurementId: 'G-Q08RGGQK4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5aXcHLfPjCDQxj_fYU1cT6gOOeVj_ZsM',
    appId: '1:1005145227491:android:e2d2238ab440c4188c85d6',
    messagingSenderId: '1005145227491',
    projectId: 'rent-bee-498712',
    storageBucket: 'rent-bee-498712.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASgq8PXF5rAJYOrETtHPOpB-5O5VtMcxM',
    appId: '1:1005145227491:ios:d21a90ffd79ef9c78c85d6',
    messagingSenderId: '1005145227491',
    projectId: 'rent-bee-498712',
    storageBucket: 'rent-bee-498712.firebasestorage.app',
    iosBundleId: 'com.rentbee.rentBee',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASgq8PXF5rAJYOrETtHPOpB-5O5VtMcxM',
    appId: '1:1005145227491:ios:d21a90ffd79ef9c78c85d6',
    messagingSenderId: '1005145227491',
    projectId: 'rent-bee-498712',
    storageBucket: 'rent-bee-498712.firebasestorage.app',
    iosBundleId: 'com.rentbee.rentBee',
  );
}
